### PR TITLE
UID-46: Add initial prereqs.

### PR DESCRIPTION
**Pull request by jim**
This is a script that we use in most projects to check that someone has the bare minimum tools available to work with the project.

To see if it works on your machine, check out this branch and run ` ./prereqs -c prereqs.conf`. You should see:

```console
$ ./prereqs -c prereqs.conf
python exists.
pipenv exists.
psql exists.
OK: all prereqs found
```

Jira issue: [UID-46]

[UID-46]: https://sfgovdt.jira.com/browse/UID-46

### CODE REVIEW

**Comment by jim** [comment]
Test

**Comment by jim** [comment]
Another test

**Comment by NamibiaTorres** [comment]
Great!

**Review by NamibiaTorres — COMMENTED** [review]
Accepting pull request.

**Pull request merged**
